### ISSUE TITLE
Exception when performing any search

### ISSUE THREAD

**Issue by BrianAllred** [jillesvangurp/es-kotlin-wrapper-client#22]
I get the error below when performing any search. I can index objects fine, just can't search. Relevant code below error message.

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found class org.elasticsearch.common.bytes.BytesReference, but interface was expected
	at io.inbot.eskotlinwrapper.ModelReaderAndWriter$DefaultImpls.deserialize(ModelReaderAndWriter.kt:33)
	at io.inbot.eskotlinwrapper.JacksonModelReaderAndWriter.deserialize(JacksonModelReaderAndWriter.kt:9)
	at io.inbot.eskotlinwrapper.SearchResults$hits$1.invoke(SearchResults.kt:33)
	at io.inbot.eskotlinwrapper.SearchResults$hits$1.invoke(SearchResults.kt:13)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at app.utils.Elastic.getLastDailyDataDocument(Elastic.kt:103)
	at app.ApplicationKt.main(Application.kt:55)
```

```
    private val esClient by lazy {
        create(
            host = "localhost",
            port = 9200,
            useSniffer = true,
            sniffAfterFailureDelayMillis = 2000,
            sniffIntervalMillis = 30000
        )
    }

    private val dailyDataRepository by lazy {
        esClient.indexRepository<DailyData>("daily-data")
    }

    fun getLastDailyDataDocument(): DailyData? {
        try {
            dailyDataRepository.search {
                source(
                    """
                {
                    "size": 1,
                    "sort": { "timestamp": "desc" },
                    "query": {
                        "match_all": {}
                    }
                }
            """.trimIndent()
                )
            }.hits.firstOrNull()

            return null
        } catch (e: Exception) {
            return null
        }
    }
```

**Comment by jillesvangurp** [comment]
Which version are you using? I had some weird classpath issues at some point where gradle was pulling in 6.x versions of some of the elastic libraries for some reason. If so, the fix is to explicitly put the correct version of these things in your dependencies until the problem goes away.

In any case, all of the code in the manual executes when the tests run so if the tests are green, master is working fine.

**Comment by BrianAllred** [comment]
Yeah, turns out I had other dependencies that were forcing elastic to default to 6.x. Thanks!
